# -*- coding: utf-8 -*-
'''
    Pitch name refers to the written (transposed) pitch for the instrument,
    as opposed to the sounding pitch.

    left hand:
        thumb: None, I, II
        index: None, down, half
        middle: None, down, d, b
        ring: None, down, cis
        pinky: None, gis, ees, b, bes, f
    right hand:
        index: None, down, gis, a
        middle: None, down, d
        ring: None, down, f
        pinky: None, c, cis, ees
'''
from abjad import *
from dissertation.tools.actions.WoodwindFingering import WoodwindFingering
oboe = instrumenttools.Oboe()
alternate_fingering_map = {
    pitchtools.NamedPitch("Eb4"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':None,
                'index':'down',
                'middle':'down',
                'ring':'down',
                'pinky':'ees',
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'down',
                'middle':'down',
                'ring':'down',
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("F4"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':None,
                'index':'down',
                'middle':'down',
                'ring':'down',
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'down',
                'middle':None,
                'ring':'down',
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("G4"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':None,
                'index':'down',
                'middle':'down',
                'ring':'down',
                'pinky':'b',
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':None,
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("Ab4"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':None,
                'index':'down',
                'middle':'down',
                'ring':'down',
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'a',
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("Bb4"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':None,
                'index':'down',
                'middle':'down',
                'ring':None,
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'down',
                'middle':'down',
                'ring':'down',
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("B4"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':None,
                'index':'down',
                'middle':'b',
                'ring':None,
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':None,
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("C5"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':None,
                'index':'down',
                'middle':None,
                'ring':None,
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':None,
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("C#5"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':None,
                'index':None,
                'middle':None,
                'ring':None,
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'down',
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("D5"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':None,
                'index':None,
                'middle':'down',
                'ring':'down',
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'down',
                'middle':'down',
                'ring':'down',
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("F5"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':'I',
                'index':'down',
                'middle':'down',
                'ring':'down',
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'down',
                'middle':None,
                'ring':'down',
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("G5"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':'I',
                'index':'down',
                'middle':'down',
                'ring':'down',
                'pinky':'b',
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':None,
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("Ab5"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':'I',
                'index':'down',
                'middle':'down',
                'ring':'down',
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'gis',
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("A5"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':'II',
                'index':'down',
                'middle':'down',
                'ring':'down',
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'down',
                'middle':'down',
                'ring':'down',
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("Bb5"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':'II',
                'index':'down',
                'middle':None,
                'ring':'down',
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':None,
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("B5"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':'II',
                'index':'down',
                'middle':None,
                'ring':'down',
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'down',
                'middle':'down',
                'ring':'down',
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("C6"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':None,
                'index':None,
                'middle':'down',
                'ring':'down',
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'down',
                'middle':'down',
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("C#6"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':'II',
                'index':None,
                'middle':None,
                'ring':None,
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'down',
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("D6"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':None,
                'index':None,
                'middle':'down',
                'ring':'down',
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':None,
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("Eb6"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':'I',
                'index':'half',
                'middle':'down',
                'ring':'down',
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':None,
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("E6"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':'I',
                'index':'half',
                'middle':'down',
                'ring':None,
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':None,
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("F6"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':'I',
                'index':'half',
                'middle':'down',
                'ring':None,
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'gis',
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("F#6"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':None,
                'index':None,
                'middle':None,
                'ring':None,
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':None,
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),
    pitchtools.NamedPitch("G6"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':'I',
                'index':'half',
                'middle':'down',
                'ring':None,
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':'down',
                'middle':None,
                'ring':None,
                'pinky':None
            }
        )
    ),

    pitchtools.NamedPitch("C#5"):(
        WoodwindFingering(
            instrument=oboe,
            hand='left',
            keys={
                'thumb':'I',
                'index':None,
                'middle':None,
                'ring':'down',
                'pinky':None,
            }
        ),
        WoodwindFingering(
            instrument=oboe,
            hand='right',
            keys={
                'index':None,
                'middle':'down',
                'ring':'down',
                'pinky':None
            }
        )
    )
}
