# -*- coding: utf-8 -*-

from abjad import *
from dissertation.materials.segment01.time_signatures import time_signatures
from dissertation.tools.RatioMaker import RatioMaker
from dissertation.tools.rhythmtools import *

ratio_makers_embouchure = (
    #1-1
    RatioMaker(
        time_signatures=time_signatures[0][0],
        rest_indices='all',
    ),
    #1-2
    RatioMaker(
        time_signatures=time_signatures[0][1],
        rest_indices='all',
    ),
    #2-1
    RatioMaker(
        time_signatures=time_signatures[1][0],
        rest_indices=(0,4,7,11),
        prolater=TrivialProlater(),
        subdivider=EvenSubdivider(1)
    ),
    #2-2
    RatioMaker(
        time_signatures=time_signatures[1][1],
        rest_indices=(0,3,5),
        prolater=TrivialProlater(unit=8),
        subdivider=EvenSubdivider(2)
    ),
    #2-3
    RatioMaker(
        time_signatures=time_signatures[1][2],
        rest_indices=(0,3,5,9,13),
        prolater=TrivialProlater(unit=16),
        subdivider=EvenSubdivider(2)
    ),
    #3-1
    RatioMaker(
        time_signatures=time_signatures[2][0],
        rest_indices=(3,4,6,7,8),
        prolater=TrivialProlater(unit=16),
        subdivider=EvenSubdivider(3)
    ),
    #3-2
    RatioMaker(
        time_signatures=time_signatures[2][1],
        rest_indices=(3,7,8,9,10),
        prolater=TrivialProlater(unit=16),
        subdivider=EvenSubdivider(3)
    ),
    #3-3
    RatioMaker(
        time_signatures=time_signatures[2][2],
        rest_indices=(1,2,3,5,6,10,11),
        prolater=TrivialProlater(unit=16),
        subdivider=EvenSubdivider(3)
    ),
    #3-4
    RatioMaker(
        time_signatures=time_signatures[2][3],
        rest_indices='all',
    ),
    #4-1
    RatioMaker(
        time_signatures=time_signatures[3][0],
        rest_indices=(0,4,7,11),
        prolater=TrivialProlater(unit=32),
        subdivider=EvenSubdivider(3)
    ),
    #4-2
    RatioMaker(
        time_signatures=time_signatures[3][1],
        rest_indices=[],
        prolater=TrivialProlater(unit=16),
        subdivider=EvenSubdivider(3)
    ),
    #4-3
    RatioMaker(
        time_signatures=time_signatures[3][2],
        rest_indices=(0,1,2,3,4,5,6,11,12),
        prolater=TrivialProlater(unit=16),
        subdivider=EvenSubdivider(3)
    ),
    #5-1
    RatioMaker(
        time_signatures=time_signatures[4][0],
        rest_indices=(2,4,8,13,16),
        prolater=TrivialProlater(unit=16),
        subdivider=EvenSubdivider(2)
    ),
    #5-2
    RatioMaker(
        time_signatures=time_signatures[4][1],
        rest_indices='all',
    ),
)
